// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FastImageConversion
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "libfic_png";
#endif
        





        /// <summary>
        ///  Only for GraphicsFormat.R8G8B8A8_UNorm
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fic_png_encode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PngEncodingResult fic_png_encode(byte* src_ptr, int src_length, uint width, uint height);

        /// <summary>
        ///  Reads the PNG header and returns the image dimensions without decoding pixels.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fic_png_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PngInfoResult fic_png_info(byte* src_ptr, int src_length);

        [DllImport(__DllName, EntryPoint = "fic_png_info_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_png_info_dispose(PngInfoResult result);

        /// <summary>
        ///  任意のPNGを RGBA8 にデコードする
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fic_png_decode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PngDecodingResult fic_png_decode(byte* src_ptr, int src_length);

        [DllImport(__DllName, EntryPoint = "fic_png_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_png_dispose(PngEncodingResult result);

        [DllImport(__DllName, EntryPoint = "fic_png_decode_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_png_decode_dispose(PngDecodingResult result);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PngEncodingResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        public ByteBuffer output;
        public byte* error_message;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PngDecodingResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        /// <summary>
        ///  RGBA8 (R,G,B,A の順で1チャンネル1バイト)
        /// </summary>
        public ByteBuffer output;
        public uint width;
        public uint height;
        public byte* error_message;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PngInfoResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        public uint width;
        public uint height;
        public byte* error_message;
    }



}
