// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FastImageConversion
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "libfic_png";
#endif
        





        /// <summary>
        ///  Only for GraphicsFormat.R8G8B8A8_UNorm
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fic_png_encode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PngEncodingResult fic_png_encode(byte* src_ptr, int src_length, uint width, uint height);

        [DllImport(__DllName, EntryPoint = "fic_png_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_png_dispose(PngEncodingResult result);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PngEncodingResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        public ByteBuffer output;
        public byte* error_message;
    }



}
