/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;




#[no_mangle]
pub unsafe extern "C" fn csbindgen_fpng_init_wrapper(

)
{
    fpng_init_wrapper(

    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_fpng_cpu_supports_sse41_wrapper(

) -> bool
{
    fpng_cpu_supports_sse41_wrapper(

    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_fpng_encode_image_to_memory_wrapper(
    image: *const c_void,
    width: u32,
    height: u32,
    num_chans: u32,
    out_data: *mut *mut u8,
    out_size: *mut usize,
    out_context: *mut *mut c_void,
    flags: u32
) -> bool
{
    fpng_encode_image_to_memory_wrapper(
        image,
        width,
        height,
        num_chans,
        out_data,
        out_size,
        out_context,
        flags
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_fpng_free_wrapper(
    context: *mut c_void
)
{
    fpng_free_wrapper(
        context
    )
}

    