// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FastImageConversion
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "libfic_fpng";
#endif
        





        [DllImport(__DllName, EntryPoint = "fpng_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fpng_init();

        [DllImport(__DllName, EntryPoint = "fpng_cpu_supports_sse41", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool fpng_cpu_supports_sse41();

        [DllImport(__DllName, EntryPoint = "fpng_encode_image_to_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool fpng_encode_image_to_memory(void* image, uint width, uint height, uint num_chans, byte** out_data, nuint* out_size, void** out_context, uint flags);

        [DllImport(__DllName, EntryPoint = "fpng_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fpng_free(void* context);


    }



}
