// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FastImageConversion
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "libfic_webp";
#endif
        





        [DllImport(__DllName, EntryPoint = "fic_webp_new_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebPConfig fic_webp_new_config(WebPPreset preset, float quality_factor);

        [DllImport(__DllName, EntryPoint = "fic_webp_encode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebpEncodingResult fic_webp_encode(byte* src_ptr, int src_length, int width, int height, WebPConfig config);

        [DllImport(__DllName, EntryPoint = "fic_webp_new_decoder_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebPDecoderOptions fic_webp_new_decoder_options();

        [DllImport(__DllName, EntryPoint = "fic_webp_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebpInfoResult fic_webp_info(byte* data_ptr, int data_length);

        [DllImport(__DllName, EntryPoint = "fic_webp_decode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern WebpDecodingResult fic_webp_decode(byte* data_ptr, int data_length, WebPDecoderOptions options);

        [DllImport(__DllName, EntryPoint = "fic_webp_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_webp_dispose(WebpEncodingResult result);

        [DllImport(__DllName, EntryPoint = "fic_webp_decode_dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void fic_webp_decode_dispose(WebpDecodingResult result);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebpEncodingResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool success;
        public ByteBuffer output;
        public WebpEncodingErrorCode error_code;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebpDecodingResult
    {
        public WebPDecBuffer output;
        public WebPBitstreamFeatures meta;
        public WebpDecodingErrorCode error_code;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct WebpInfoResult
    {
        public WebPBitstreamFeatures meta;
        public WebpDecodingErrorCode error_code;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
    }


    internal enum WebpEncodingErrorCode : uint
    {
        None = 0,
        OutOfMemory = 1,
        BitstreamOutOfMemory = 2,
        NullParameter = 3,
        InvalidConfiguration = 4,
        BadDimension = 5,
        Partition0Overflow = 6,
        PartitionOverflow = 7,
        BadWrite = 8,
        FileTooBig = 9,
        UserAbort = 10,
        Last = 11,
    }

    internal enum WebpDecodingErrorCode : uint
    {
        None = 0,
        OutOfMemory = 1,
        InvalidParam = 2,
        BitstreamError = 3,
        UnsupportedFeature = 4,
        Suspended = 5,
        UserAbort = 6,
        NotEnoughData = 7,
    }


}
